### ISSUE TITLE
Unable to build my Android project on linux

### ISSUE THREAD

**Issue by dhartwich1991** [gojuno/mainframer#146] opened 2017-02-07 13:52 UTC
Hey there, I get the following error, when trying to compile my project on ubuntu 16.04 

```
[...]
:core-app:prepareDebugDependencies
:core-app:compileDebugAidl FAILED

BUILD FAILED

Total time: 1.064 secs
/opt/android/sdk/build-tools/24.0.3/aidl: 1: /opt/android/sdk/build-tools/24.0.3/aidl: ELF: not found
/opt/android/sdk/build-tools/24.0.3/aidl: 2: /opt/android/sdk/build-tools/24.0.3/aidl: �: not found
/opt/android/sdk/build-tools/24.0.3/aidl: 3: /opt/android/sdk/build-tools/24.0.3/aidl: �: not found
/opt/android/sdk/build-tools/24.0.3/aidl: 4: /opt/android/sdk/build-tools/24.0.3/aidl: �: not found
/opt/android/sdk/build-tools/24.0.3/aidl: 5: /opt/android/sdk/build-tools/24.0.3/aidl: �: not found
/opt/android/sdk/build-tools/24.0.3/aidl: 6: /opt/android/sdk/build-tools/24.0.3/aidl: �: not found
/opt/android/sdk/build-tools/24.0.3/aidl: 7: /opt/android/sdk/build-tools/24.0.3/aidl: �: not found
/opt/android/sdk/build-tools/24.0.3/aidl: 9: /opt/android/sdk/build-tools/24.0.3/aidl: ���)/6=DJPW^elr{������$.5Dbi��������
I: not found
'
�: not found
�: not found
�o�!��/�: not found
/opt/android/sdk/build-tools/24.0.3/aidl: 13: /opt/android/sdk/build-tools/24.0.3/aidl: Syntax error: "(" unexpected


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':core-app:compileDebugAidl'.
> java.lang.RuntimeException: com.android.ide.common.process.ProcessException: Error while executing '/opt/android/sdk/build-tools/24.0.3/aidl' with arguments {-p/opt/android/sdk/platforms/android-24/framework.aidl -o/home/daniel_hartwich/mainframer/android-app/core-app/build/generated/source/aidl/debug -I/home/daniel_hartwich/mainframer/android-app/core-app/src/main/aidl -I/home/daniel_hartwich/mainframer/android-app/core-app/src/debug/aidl -I/home/daniel_hartwich/mainframer/android-app/core-app/build/intermediates/exploded-aar/com.jakewharton/butterknife/8.5.1/aidl -I/home/daniel_hartwich/mainframer/android-app/core-app/build/intermediates/exploded-aar/com.jakewharton.timber/timber/4.5.1/aidl -I/home/daniel_hartwich/mainframer/android-app/core-app/build/intermediates/exploded-aar/com.f2prateek.rx.preferences/rx-preferences/1.0.2/aidl -I/home/daniel_hartwich/mainframer/android-app/core-app/build/intermediates/exploded-aar/com.android.support/customtabs/25.0.0/aidl -I/home/daniel_hartwich/mainframer/android-app/core-app/build/intermediates/exploded-aar/com.squareup.sqlbrite/sqlbrite/0.7.0/aidl -I/home/daniel_hartwich/mainframer/android-app/core-app/build/intermediates/exploded-aar/com.github.Shyish/GenericRenderers/2.1.1/aidl -I/home/daniel_hartwich/mainframer/android-app/core-app/build/intermediates/exploded-aar/com.github.Shyish/CheckView/1.0.4/aidl -I/home/daniel_hartwich/mainframer/android-app/core-app/build/intermediates/exploded-aar/com.andkulikov/transitionseverywhere/1.6.9/aidl -I/home/daniel_hartwich/mainframer/android-app/core-app/build/intermediates/exploded-aar/com.soundcloud.android/android-crop/1.0.1/aidl -I/home/daniel_hartwich/mainframer/android-app/core-app/build/intermediates/exploded-aar/net.hockeyapp.android/HockeySDK/4.1.1/aidl -I/home/daniel_hartwich/mainframer/android-app/core-app/build/intermediates/exploded-aar/de.interrogare.lib/interrogareSurvey-lib/1.4.0/aidl -I/home/daniel_hartwich/mainframer/android-app/core-app/build/intermediates/exploded-aar/nl.littlerobots.rxlint/rxlint/1.0/aidl -I/home/daniel_hartwich/mainframer/android-app/core-app/build/intermediates/exploded-aar/com.jakewharton.rxbinding/rxbinding-design/1.0.0/aidl -I/home/daniel_hartwich/mainframer/android-app/core-app/build/intermediates/exploded-aar/com.jakewharton.rxbinding/rxbinding/1.0.0/aidl -I/home/daniel_hartwich/mainframer/android-app/core-app/build/intermediates/exploded-aar/io.reactivex/rxandroid/1.2.1/aidl -I/home/daniel_hartwich/mainframer/android-app/core-app/build/intermediates/exploded-aar/com.xing.android/alibaba/1.0.7/aidl -I/home/daniel_hartwich/mainframer/android-app/core-app/build/intermediates/exploded-aar/com.xing.api.jobs/xing-android-jobs-sdk/0.1.29/aidl -I/home/daniel_hartwich/mainframer/android-app/core-app/build/intermediates/exploded-aar/com.xing.android/xing-ui/1.3.244/aidl -I/home/daniel_hartwich/mainframer/android-app/core-app/build/intermediates/exploded-aar/us.feras.mdv/markdownview/1.1.1/aidl -I/home/daniel_hartwich/mainframer/android-app/core-app/build/intermediates/exploded-aar/com.android.support/cardview-v7/25.0.0/aidl -I/home/daniel_hartwich/mainframer/android-app/core-app/build/intermediates/exploded-aar/com.android.support/design/25.0.1/aidl -I/home/daniel_hartwich/mainframer/android-app/core-app/build/intermediates/exploded-aar/com.android.support/appcompat-v7/25.0.1/aidl -I/home/daniel_hartwich/mainframer/android-app/core-app/build/intermediates/exploded-aar/com.android.support/animated-vector-drawable/25.0.1/aidl -I/home/daniel_hartwich/mainframer/android-app/core-app/build/intermediates/exploded-aar/com.android.support/support-vector-drawable/25.0.1/aidl -I/home/daniel_hartwich/mainframer/android-app/core-app/build/intermediates/exploded-aar/com.android.support/recyclerview-v7/25.0.1/aidl -I/home/daniel_hartwich/mainframer/android-app/core-app/build/intermediates/exploded-aar/com.android.support/transition/25.0.1/aidl -I/home/daniel_hartwich/mainframer/android-app/core-app/build/intermediates/exploded-aar/com.android.support/support-v4/25.0.1/aidl -I/home/daniel_hartwich/mainframer/android-app/core-app/build/intermediates/exploded-aar/com.android.support/support-fragment/25.0.1/aidl -I/home/daniel_hartwich/mainframer/android-app/core-app/build/intermediates/exploded-aar/com.android.support/support-media-compat/25.0.1/aidl -I/home/daniel_hartwich/mainframer/android-app/core-app/build/intermediates/exploded-aar/com.android.support/support-core-ui/25.0.1/aidl -I/home/daniel_hartwich/mainframer/android-app/core-app/build/intermediates/exploded-aar/com.android.support/support-core-utils/25.0.1/aidl -I/home/daniel_hartwich/mainframer/android-app/core-app/build/intermediates/exploded-aar/com.android.support/percent/25.0.0/aidl -I/home/daniel_hartwich/mainframer/android-app/core-app/build/intermediates/exploded-aar/com.android.support/support-compat/25.1.0/aidl -I/home/daniel_hartwich/mainframer/android-app/core-app/build/intermediates/exploded-aar/com.timehop.stickyheadersrecyclerview/library/0.4.2/aidl -I/home/daniel_hartwich/mainframer/android-app/core-app/build/intermediates/exploded-aar/jp.wasabeef/picasso-transformations/2.1.0/aidl -I/home/daniel_hartwich/mainframer/android-app/core-app/build/intermediates/exploded-aar/com.xing.tracking/alfred/2.5.37/aidl -I/home/daniel_hartwich/mainframer/android-app/core-app/build/intermediates/exploded-aar/de.infonline/infonline/1.1.5/aidl -I/home/daniel_hartwich/mainframer/android-app/core-app/build/intermediates/exploded-aar/com.squareup.sqldelight/runtime/0.4.4/aidl -d/tmp/aidl8096967891856258650.d /home/daniel_hartwich/mainframer/android-app/core-app/src/main/aidl/com/android/vending/billing/IInAppBillingService.aidl}

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.


```

I have no why this could be happening, can you suggest something? I know this is not really related to mainframer but I am trying to enable mainframer right now but this is standing in my way.

Help is very much appreciated. Compiling on my mac works without problems but is slow as hell.

Cheers!

**Comment by dhartwich1991** [comment] 2017-02-07 13:56
I removed the aidl file from the project just to see what's happening and it fails on merging debug resources with a similar error:

```
AAPT err(Facade for 29747011): /opt/android/sdk/build-tools/24.0.3/aapt: 1: /opt/android/sdk/build-tools/24.0.3/aapt: : not found
AAPT err(Facade for 29747011): /opt/android/sdk/build-tools/24.0.3/aapt: 1: /opt/android/sdk/build-tools/24.0.3/aapt: ELF: not found
AAPT err(Facade for 29747011): /opt/android/sdk/build-tools/24.0.3/aapt: 1: /opt/android/sdk/build-tools/24.0.3/aapt: BIPWo������������5[����������������: not found
AAPT err(Facade for 29747011): /opt/android/sdk/build-tools/24.0.3/aapt: 2: /opt/android/sdk/build-tools/24.0.3/aapt: Syntax error: ")" unexpected
AAPT err(Facade for 9662893): /opt/android/sdk/build-tools/24.0.3/aapt: 1: /opt/android/sdk/build-tools/24.0.3/aapt: : not found
AAPT err(Facade for 9662893): /opt/android/sdk/build-tools/24.0.3/aapt: 1: /opt/android/sdk/build-tools/24.0.3/aapt: ELF: not found
AAPT err(Facade for 9662893): /opt/android/sdk/build-tools/24.0.3/aapt: 1: /opt/android/sdk/build-tools/24.0.3/aapt: BIPWo������������5[����������������: not found
AAPT err(Facade for 9662893): /opt/android/sdk/build-tools/24.0.3/aapt: 2: /opt/android/sdk/build-tools/24.0.3/aapt: Syntax error: ")" unexpected
AAPT err(Facade for 3212340): /opt/android/sdk/build-tools/24.0.3/aapt: 1: /opt/android/sdk/build-tools/24.0.3/aapt: : not found
AAPT err(Facade for 3212340): /opt/android/sdk/build-tools/24.0.3/aapt: 1: /opt/android/sdk/build-tools/24.0.3/aapt: ELF: not found
AAPT err(Facade for 3212340): /opt/android/sdk/build-tools/24.0.3/aapt: 1: /opt/android/sdk/build-tools/24.0.3/aapt: BIPWo������������5[����������������: not found
AAPT err(Facade for 3212340): /opt/android/sdk/build-tools/24.0.3/aapt: 2: /opt/android/sdk/build-tools/24.0.3/aapt: Syntax error: ")" unexpected
```

**Comment by artem-zinnatullin** [comment] 2017-02-07 14:03
Disclaimer for others who might open this issue: it's not related to mainframer, it's about building android project on Ubuntu.

---


Hello, @dhartwich1991!

A guess I have at the moment is that you need to `apt-get install lib32stdc++6 lib32z1` packages on remote machine in order to make `aapt` work, see this [SO question](https://stackoverflow.com/questions/18928164/android-studio-cannot-find-aapt).

Would be helpful to see more info about your remote machine, `uname -a` for example.

**Comment by dhartwich1991** [comment] 2017-02-07 14:08
Thanks @artem-zinnatullin for the fast response.

Output of uname -a
```
Linux mainframer-root 4.4.0-31-generic #50-Ubuntu SMP Wed Jul 13 00:06:14 UTC 2016 i686 i686 i686 GNU/Linux
```

When I try to install the above tools I get the following errors:

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package lib32stdc++6
E: Couldn't find any package by regex 'lib32stdc++6'
E: Unable to locate package lib32z1
```

**Comment by artem-zinnatullin** [comment] 2017-02-07 14:24
Ok, so the problem is that you're running 32-bit Linux (`i686`), Android Tools team [dropped support](https://code.google.com/p/android/issues/detail?id=196866) for 32-bit systems in the end of 2014.

My best suggestion is to get 64-bit machine and install 64-bit Ubuntu on it.

I'm closing this then, feel free to continue conversation though :)

**Closed as completed by artem-zinnatullin** 2017-02-07 14:24 UTC
Labels: notblocking

**Comment by dhartwich1991** [comment] 2017-02-07 14:41
@artem-zinnatullin Thank you :/ Getting a 64-bit machine now and installing once again...hope that it works afterwards.

**Comment by artem-zinnatullin** [comment] 2017-02-07 14:57
Great! Btw, make sure you've read whole README of [`gradle-android` sample](https://github.com/gojuno/mainframer/tree/development/samples/gradle-android), you'll find instructions on how to setup IDE and also how to auto-download Android sdk components on remote machine.
